"""Criticality map for SCH / Chapter 1.

SCH itself fixes the architecture to one shared trait axis. Under the current
convex quadratic benchmark, changing functional weights moves the shared optimum
continuously; there is no intrinsic shared-vs-differentiated phase switch inside
that one-axis world.

This module therefore keeps three boundaries separate:

1. intrinsic conflict onset in the shared world (shared conflict load = 0),
2. a Chapter-1 projection of the cross-architecture boundary after importing
   decoupling/cost information from BITA (s * L_S* = K), and
3. empirical state-optimum geometry, which is not automatically on the same
   fitness scale as the architecture boundary.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def _finite(value: float, name: str) -> float:
    value = float(value)
    if not math.isfinite(value):
        raise ValueError(f"{name} must be finite")
    return value


def _positive(value: float, name: str) -> float:
    value = _finite(value, name)
    if value <= 0:
        raise ValueError(f"{name} must be > 0")
    return value


def _nonnegative(value: float, name: str) -> float:
    value = _finite(value, name)
    if value < 0:
        raise ValueError(f"{name} must be >= 0")
    return value


def shared_optimum(theta1: float, theta2: float, weight1: float = 1.0, weight2: float = 1.0) -> float:
    theta1 = _finite(theta1, "theta1")
    theta2 = _finite(theta2, "theta2")
    weight1 = _positive(weight1, "weight1")
    weight2 = _positive(weight2, "weight2")
    return (weight1 * theta1 + weight2 * theta2) / (weight1 + weight2)


def shared_conflict_load(theta1: float, theta2: float, weight1: float = 1.0, weight2: float = 1.0) -> float:
    theta1 = _finite(theta1, "theta1")
    theta2 = _finite(theta2, "theta2")
    weight1 = _positive(weight1, "weight1")
    weight2 = _positive(weight2, "weight2")
    delta = theta1 - theta2
    return weight1 * weight2 * delta * delta / (weight1 + weight2)


def decoupling_fraction(weight1: float = 1.0, weight2: float = 1.0, coupling: float = 0.0) -> float:
    weight1 = _positive(weight1, "weight1")
    weight2 = _positive(weight2, "weight2")
    coupling = _nonnegative(coupling, "coupling")
    numerator = weight1 * weight2
    return numerator / (numerator + coupling * (weight1 + weight2))


def projected_critical_conflict_load(architecture_cost: float, decoupling: float) -> float:
    architecture_cost = _nonnegative(architecture_cost, "architecture_cost")
    decoupling = _nonnegative(decoupling, "decoupling")
    if decoupling > 1:
        raise ValueError("decoupling must be <= 1")
    if decoupling == 0:
        return 0.0 if architecture_cost == 0 else math.inf
    return architecture_cost / decoupling


def projected_critical_optimum_distance(
    architecture_cost: float,
    weight1: float = 1.0,
    weight2: float = 1.0,
    coupling: float = 0.0,
) -> float:
    """Critical |theta1-theta2| implied by the common quadratic boundary.

    Solves s * L_S* = K for the function-optimum distance. This is a
    cross-world projection, not an intrinsic phase transition generated by SCH
    alone.
    """

    architecture_cost = _nonnegative(architecture_cost, "architecture_cost")
    weight1 = _positive(weight1, "weight1")
    weight2 = _positive(weight2, "weight2")
    coupling = _nonnegative(coupling, "coupling")
    if architecture_cost == 0:
        return 0.0
    numerator = architecture_cost * (weight1 + weight2) * (
        weight1 * weight2 + coupling * (weight1 + weight2)
    )
    denominator = weight1 * weight1 * weight2 * weight2
    return math.sqrt(numerator / denominator)


def projected_architecture_margin(
    theta1: float,
    theta2: float,
    architecture_cost: float,
    weight1: float = 1.0,
    weight2: float = 1.0,
    coupling: float = 0.0,
) -> float:
    load = shared_conflict_load(theta1, theta2, weight1, weight2)
    s = decoupling_fraction(weight1, weight2, coupling)
    return s * load - _nonnegative(architecture_cost, "architecture_cost")


def classify_projected_boundary(margin: float, tolerance: float = 1e-12) -> str:
    margin = _finite(margin, "margin")
    tolerance = _nonnegative(tolerance, "tolerance")
    if margin > tolerance:
        return "DIFFERENTIATED_WORLD_FAVOURED_IF_AVAILABLE"
    if margin < -tolerance:
        return "SHARED_WORLD_RETAINS_ARCHITECTURE_ADVANTAGE"
    return "COMMON_ARCHITECTURE_CRITICAL_SURFACE"


def empirical_state_geometry(z_p: float, z_g: float, z_c: float) -> dict:
    z_p = _finite(z_p, "z_p")
    z_g = _finite(z_g, "z_g")
    z_c = _finite(z_c, "z_c")
    lo, hi = sorted((z_p, z_g))
    return {
        "state_optimum_separation": abs(z_p - z_g),
        "combined_inside_state_interval": lo <= z_c <= hi,
        "distance_combined_to_function1_state": abs(z_c - z_p),
        "distance_combined_to_function2_state": abs(z_c - z_g),
        "intrinsic_state_conflict_boundary": "z_P* = z_G*",
        "architecture_critical_point_status": (
            "NOT_IDENTIFIED_FROM_STATE_OPTIMA_ALONE; requires a commensurable fitness-loss map plus BITA decoupling/cost"
        ),
    }


def criticality_report(config: dict) -> dict:
    theta1 = float(config["theta1"])
    theta2 = float(config["theta2"])
    w1 = float(config.get("weight1", 1.0))
    w2 = float(config.get("weight2", 1.0))
    coupling = float(config.get("coupling", 0.0))
    cost = float(config.get("architecture_cost", 0.0))

    load = shared_conflict_load(theta1, theta2, w1, w2)
    s = decoupling_fraction(w1, w2, coupling)
    margin = s * load - cost
    report = {
        "chapter": "SCH_CHAPTER_1_BALANCE",
        "shared_optimum": shared_optimum(theta1, theta2, w1, w2),
        "shared_conflict_load": load,
        "intrinsic_conflict_margin": load,
        "intrinsic_conflict_boundary": "L_S*=0 (theta1=theta2, or a focal functional weight vanishes in the limiting model)",
        "fixed_one_axis_phase_switch": "NONE_IN_CURRENT_UNBOUNDED_CONVEX_QUADRATIC_MODEL",
        "imported_bita_decoupling_fraction": s,
        "imported_bita_architecture_cost": cost,
        "projected_critical_conflict_load": projected_critical_conflict_load(cost, s),
        "projected_critical_optimum_distance": projected_critical_optimum_distance(cost, w1, w2, coupling),
        "projected_architecture_margin": margin,
        "projected_architecture_status": classify_projected_boundary(margin),
        "critical_surface_identity": "s*L_S* = K",
        "interpretation": (
            "The Chapter-1 critical load is a projection of the cross-architecture boundary. "
            "SCH alone supplies conflict geometry/load; the architecture switch requires BITA decoupling and cost."
        ),
    }
    if all(key in config for key in ("z_P", "z_G", "z_C")):
        report["empirical_state_geometry"] = empirical_state_geometry(
            float(config["z_P"]), float(config["z_G"]), float(config["z_C"])
        )
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("config", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    config = json.loads(args.config.read_text(encoding="utf-8"))
    result = criticality_report(config)
    text = json.dumps(result, indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
