"""Project the common SCH/BITA architecture boundary onto a Chapter-1 functional weight.

Within SCH's fixed one-axis world, changing a functional weight moves the shared
optimum continuously. The threshold computed here is therefore not an intrinsic
phase transition generated by SCH alone. It is the value of the context-dependent
function-2 weight at which the imported BITA architecture comparison satisfies
s*L_S*=K.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def _finite(value: float, name: str) -> float:
    value = float(value)
    if not math.isfinite(value):
        raise ValueError(f"{name} must be finite")
    return value


def _positive(value: float, name: str) -> float:
    value = _finite(value, name)
    if value <= 0:
        raise ValueError(f"{name} must be > 0")
    return value


def _nonnegative(value: float, name: str) -> float:
    value = _finite(value, name)
    if value < 0:
        raise ValueError(f"{name} must be >= 0")
    return value


def recoverable_loss(function2_weight: float, function1_weight: float, coupling: float, optimum_distance: float) -> float:
    b = _nonnegative(function2_weight, "function2_weight")
    a = _positive(function1_weight, "function1_weight")
    lam = _nonnegative(coupling, "coupling")
    d = _nonnegative(optimum_distance, "optimum_distance")
    if b == 0 or d == 0:
        return 0.0
    return a * a * b * b * d * d / ((a + b) * (a * b + lam * (a + b)))


def asymptotic_recovery(function1_weight: float, coupling: float, optimum_distance: float) -> float:
    a = _positive(function1_weight, "function1_weight")
    lam = _nonnegative(coupling, "coupling")
    d = _nonnegative(optimum_distance, "optimum_distance")
    return a * a * d * d / (a + lam)


def solve_critical_function2_weight(
    function1_weight: float,
    coupling: float,
    optimum_distance: float,
    architecture_cost: float,
    tolerance: float = 1e-12,
) -> dict:
    a = _positive(function1_weight, "function1_weight")
    lam = _nonnegative(coupling, "coupling")
    d = _nonnegative(optimum_distance, "optimum_distance")
    K = _nonnegative(architecture_cost, "architecture_cost")
    tol = _nonnegative(tolerance, "tolerance")
    ceiling = asymptotic_recovery(a, lam, d)

    if d == 0:
        if K <= tol:
            return {
                "critical_function2_weight": 0.0,
                "status": "ALL_WEIGHTS_ON_ZERO_CONFLICT_BOUNDARY",
                "asymptotic_recoverable_loss": ceiling,
            }
        return {
            "critical_function2_weight": None,
            "status": "NO_CONFLICT_SHARED_WORLD_ALWAYS_FAVOURED",
            "asymptotic_recoverable_loss": ceiling,
        }

    if K <= tol:
        return {
            "critical_function2_weight": 0.0,
            "status": "ZERO_COST_COLLAPSES_PROJECTED_ARCHITECTURE_THRESHOLD_TO_CONFLICT_ONSET",
            "asymptotic_recoverable_loss": ceiling,
        }

    scale = max(1.0, abs(K), abs(ceiling))
    if abs(K - ceiling) <= tol * scale:
        return {
            "critical_function2_weight": math.inf,
            "status": "ASYMPTOTIC_CRITICAL_WEIGHT_NO_FINITE_CROSSING",
            "asymptotic_recoverable_loss": ceiling,
        }
    if K > ceiling:
        return {
            "critical_function2_weight": None,
            "status": "COST_EXCEEDS_MAX_RECOVERABLE_LOSS_BALANCE_ONLY",
            "asymptotic_recoverable_loss": ceiling,
        }

    A = a * a * d * d - K * (a + lam)
    discriminant = K * K * (a + 2.0 * lam) ** 2 + 4.0 * K * lam * A
    bcrit = a * (K * (a + 2.0 * lam) + math.sqrt(discriminant)) / (2.0 * A)
    return {
        "critical_function2_weight": bcrit,
        "status": "FINITE_PROJECTED_FUNCTION2_WEIGHT_CRITICAL_POINT",
        "asymptotic_recoverable_loss": ceiling,
    }


def report(config: dict) -> dict:
    a = float(config["function1_weight"])
    lam = float(config.get("coupling", 0.0))
    d = float(config["optimum_distance"])
    K = float(config["architecture_cost"])
    result = solve_critical_function2_weight(a, lam, d, K)
    result.update(
        {
            "chapter": "SCH_CHAPTER_1_BALANCE",
            "function1_weight": a,
            "coupling_imported_from_bita": lam,
            "optimum_distance": d,
            "architecture_cost_imported_from_bita": K,
            "critical_surface_identity": "s(b)*L_S*(b)=K",
            "intrinsic_sch_phase_switch": "NONE_IN_CURRENT_CONVEX_ONE_AXIS_MODEL",
            "interpretation": (
                "This is the Chapter-1 projection of the shared architecture boundary. "
                "It is not an intrinsic discontinuity of the one-axis SCH optimum."
            ),
        }
    )
    bcrit = result["critical_function2_weight"]
    if isinstance(bcrit, (int, float)) and math.isfinite(bcrit):
        result["boundary_recoverable_loss"] = recoverable_loss(bcrit, a, lam, d)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("config", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    config = json.loads(args.config.read_text(encoding="utf-8"))
    result = report(config)
    text = json.dumps(result, indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
